theme: minima

header_pages:
  - index.md
  - research.md
  - cv.md
  - teaching.md 
  - other.md


locale                   : "en-US"
title                    : "Véra Zabrodina"
site.title               : "Véra Zabrodina"
title_separator          : "-"
name                     : &name "Véra Zabrodina"
description              : &description "Véra Zabrodina's personal website. Copyright 2021."

plugins:
  - jekyll-redirect-from