theme: minima

header_pages:
  - about.md
  - research.md
  - teaching.md 
  - other.md


locale                   : "en-US"
title                    : "Véra Zabrodina | Personal website"
site.title               : "Véra Zabrodina | Personal website"
title_separator          : "-"
name                     : &name "Véra Zabrodina"
description              : &description "Ph.D. Candidate in Economics"